#!/bin/bash

# Show Template Help Script
# Displays available parameters for each template

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}Inflop.ConsoleApp.Templates - Parameters${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

echo -e "${GREEN}Common Parameters (all templates):${NC}"
echo ""
echo "  -F, --Framework <net8.0|net9.0>"
echo "      Target framework (default: net8.0)"
echo ""
echo "  --use-async <true|false>"
echo "      Enable async/await pattern"
echo "      - inflop-simple:     default false (synchronous)"
echo "      - other templates:   default true (asynchronous)"
echo ""
echo "  --add-serilog"
echo "      Add Serilog logging integration"
echo ""
echo "  --add-docker"
echo "      Add Docker support (Dockerfile, .dockerignore, docker-compose.yml)"
echo ""
echo "  --add-command-line <none|system-commandline|spectre-console|command-line-parser>"
echo "      Add command-line argument parsing library"
echo "      - none:                No CLI library (default)"
echo "      - system-commandline:  System.CommandLine (Microsoft official)"
echo "      - spectre-console:     Spectre.Console (rich UI)"
echo "      - command-line-parser: CommandLineParser (attribute-based)"
echo ""
echo "  --add-database <none|dapper|efcore>"
echo "      Add database access support"
echo "      - none:    No database (default)"
echo "      - dapper:  Dapper micro-ORM"
echo "      - efcore:  Entity Framework Core"
echo ""
echo "  --database-type <sqlite|sqlserver|postgres>"
echo "      Database provider (only when --add-database != none)"
echo "      - sqlite:     SQLite (default, file-based)"
echo "      - sqlserver:  Microsoft SQL Server"
echo "      - postgres:   PostgreSQL"
echo ""
echo "  --add-http-client <none|basic|with-polly>"
echo "      Add HTTP client support"
echo "      - none:        No HTTP client (default)"
echo "      - basic:       Basic typed HttpClient"
echo "      - with-polly:  HttpClient with Polly resilience policies"
echo ""
echo "  --add-health-checks <none|basic|aspnet>"
echo "      Add health checks support"
echo "      - none:    No health checks (default)"
echo "      - basic:   Basic health checks (programmatic)"
echo "      - aspnet:  Health checks with ASP.NET endpoint"
echo ""
echo "  --add-messaging <none|rabbitmq|azureservicebus|kafka>"
echo "      Add message queue support"
echo "      - none:             No messaging (default)"
echo "      - rabbitmq:         RabbitMQ"
echo "      - azureservicebus:  Azure Service Bus"
echo "      - kafka:            Apache Kafka"
echo ""

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}Template-Specific Information${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

echo -e "${GREEN}1. inflop-simple${NC} - Simple DI Console App"
echo "   Default async: false (synchronous)"
echo "   Pattern:       Manual ServiceCollection setup"
echo "   Best for:      Learning, simple scripts"
echo ""

echo -e "${GREEN}2. inflop-standard${NC} - Standard Generic Host"
echo "   Default async: true (asynchronous)"
echo "   Pattern:       Generic Host with BackgroundService"
echo "   Best for:      Production applications, long-running workers"
echo ""

echo -e "${GREEN}3. inflop-advanced${NC} - Advanced Top-Level Statements"
echo "   Default async: true (asynchronous)"
echo "   Pattern:       Extension methods for service registration"
echo "   Best for:      Medium to large applications, clean architecture"
echo ""

echo -e "${GREEN}4. inflop-enterprise${NC} - Enterprise Clean Architecture"
echo "   Default async: true (asynchronous)"
echo "   Pattern:       Strongly-typed configuration, Options pattern"
echo "   Best for:      Large applications, enterprise scenarios"
echo ""

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}Usage Examples${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

echo -e "${YELLOW}# Default (minimal) configuration${NC}"
echo "dotnet new inflop-simple -n MyApp"
echo ""

echo -e "${YELLOW}# With Serilog logging${NC}"
echo "dotnet new inflop-simple -n MyApp --add-serilog"
echo ""

echo -e "${YELLOW}# With database (EF Core + SQLite)${NC}"
echo "dotnet new inflop-simple -n MyApp --add-database efcore --database-type sqlite"
echo ""

echo -e "${YELLOW}# With HTTP client and Polly${NC}"
echo "dotnet new inflop-simple -n MyApp --add-http-client with-polly"
echo ""

echo -e "${YELLOW}# Full featured application${NC}"
echo "dotnet new inflop-enterprise -n MyApp \\"
echo "  -F net9.0 \\"
echo "  --use-async true \\"
echo "  --add-serilog \\"
echo "  --add-docker \\"
echo "  --add-command-line spectre-console \\"
echo "  --add-database efcore \\"
echo "  --database-type postgres \\"
echo "  --add-http-client with-polly \\"
echo "  --add-health-checks aspnet \\"
echo "  --add-messaging rabbitmq"
echo ""

echo -e "${YELLOW}# .NET 9.0 with async and database${NC}"
echo "dotnet new inflop-standard -n MyWorker \\"
echo "  -F net9.0 \\"
echo "  --add-database dapper \\"
echo "  --database-type sqlserver"
echo ""

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}Get Template-Specific Help${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

echo "dotnet new inflop-simple --help"
echo "dotnet new inflop-standard --help"
echo "dotnet new inflop-advanced --help"
echo "dotnet new inflop-enterprise --help"
echo ""

echo -e "${BLUE}=========================================${NC}"
echo -e "${BLUE}Testing${NC}"
echo -e "${BLUE}=========================================${NC}"
echo ""

echo "# Test all templates comprehensively"
echo "./test-all-templates.sh"
echo ""

echo "# Test single template"
echo "./test-single-template.sh inflop-simple MyTest --add-serilog"
echo ""

echo -e "${BLUE}=========================================${NC}"
